name: clear_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  flutter_animate: ^4.1.0
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5
  provider: ^6.0.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  # This is the new, required flag for code generation.
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"
  min_sdk_android: 21 # Recommended for most modern apps
